// THIS FILE IS AUTOGENERATED. TO UPDATE, RUN
//    dart tool/generate_asset_hashes.dart

const assetHashes = <String, String>{
  'libpixer_android_arm64.so': 'e90fcdb02754f8b2d5d6f8bd97dc08c1',
  'libpixer_android_armv7.so': 'c6b79b73972435e07a6c10d92c84e493',
  'libpixer_android_x86_64.so': 'd1a5a0d3aa678344e23acf48d1688157',
  'libpixer_ios_arm64.dylib': 'b0818e2b022a8acfc002b9c16103fd8f',
  'libpixer_ios_sim_arm64.dylib': '04d2c4a570a06121d61cca046dc9216a',
  'libpixer_ios_sim_x86_64.dylib': 'd6971ea14c0fc41d0783c80ed6d7b29f',
  'libpixer_linux_aarch64.so': '892ae0575723470e16574f54091bdfbe',
  'libpixer_linux_x86_64.so': 'dd55ce5d3b93a3ecd482aa009b97c68b',
  'libpixer_macos_arm64.dylib': '628df6e601e9d3b942993ada433a5f9d',
  'libpixer_macos_x86_64.dylib': '843f566787e23ef6687f216b43f658f3',
  'pixer_windows_arm64.dll': 'bd2509169c0648aa3946ef72fa281121',
  'pixer_windows_x86_64.dll': 'cf1310f8de1fad9e804e62cab326c62c',
};
